### ISSUE TITLE
Stow only installs the dotfiles in the right directory if the repository got cloned to ~

### ISSUE THREAD

**Issue by sinewavess** [JackMechem/dotfiles#1]
My dotfiles repo is named "dotfiles" too, so i git cloned the repo into my Documents folder, cded to it, and ran `stow .`, as the readme said. but instead of moving the files to my home, it moved them to my user folder. I don't know how stow works, and i don't know if you can fix it, i just thought it'd be nice letting you know

**Comment by JackMechem** [comment]
Oh thanks. Yeah I abandoned this repo and only look at it every month or so. I'm not sure how I had stow setup as I don't use it anymore.
